# Generated by Django 5.2.12 on 2026-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(max_length=60)),
                ('project_slug', models.SlugField(max_length=64)),
                ('reason', models.TextField()),
                ('expires_in_days', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('dispatched', 'dispatched'), ('validation_failed', 'validation_failed'), ('request_started', 'request_started')], max_length=20)),
                ('source', models.CharField(choices=[('backend', 'backend'), ('signal', 'signal')], max_length=10)),
                ('step', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('field_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
