# Generated by Django 6.0.4 on 2026-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auditentry_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='access_layer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='access_reason',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='kind',
            field=models.CharField(choices=[('dispatched', 'dispatched'), ('validation_failed', 'validation_failed'), ('request_started', 'request_started'), ('access_denied', 'access_denied')], max_length=20),
        ),
    ]
