# Generated by Django 6.0.4 on 2026-05-12 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=32)),
                ('app_label', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin activity',
                'verbose_name_plural': 'admin activity',
                'ordering': ['-timestamp'],
            },
        ),
    ]
