# Generated by Django 6.0.4 on 2026-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_demo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
