# Generated by Django 6.1 on 2026-09-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_locked_tenant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme',
            field=models.CharField(choices=[('shared', 'Shared default'), ('acme', 'Acme blue')], default='shared', max_length=16),
        ),
    ]
