# Generated by Django 6.1 on 2026-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_locked_tenant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stylesheet',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
