[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py tests.py
DJANGO_SETTINGS_MODULE = config.settings
markers =
    django_db: tests that use the Django database
addopts = -p no:benchmark
