# Generated by Django 6.1 on 2026-09-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_catalog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_cat_stock_idx',
            old_name='catalog_pro_category_cafcbf_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_price_idx',
            old_name='catalog_pro_price_2d2a4c_idx',
        ),
    ]
