# Generated by Django 6.0.4 on 2026-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
