from __future__ import annotations

from tests.support.attribution import (
    handler_declared_here,
    unwrapped_decorator,
    wraps_decorator,
)
from tests.support.backends import (
    BOOM_COMPONENTS_BACKEND,
    DUMMY_COMPONENTS_BACKEND,
    MALFORMED_WATCH_COMPONENTS_BACKEND,
    RAISING_WATCH_COMPONENTS_BACKEND,
    BoomComponentsBackend,
    DummyComponentsBackend,
    MockAutoreloadSender,
    PlainStaticBackend,
    RecordingStaticBackend,
    StaticAssetProvider,
    WatchingComponentsBackend,
    failing_watch_components_entry,
    file_components_entry,
    watching_components_entry,
)
from tests.support.cases import (
    COERCE_URL_VALUE_CASES,
    URL_BY_ANNOTATION_RESOLVE_CASES,
    URL_KWARGS_RESOLVE_CASES,
    CoerceUrlValueCase,
    ContextMarkerCase,
    PlanCase,
    UrlByAnnotationResolveCase,
    UrlKwargsResolveCase,
)
from tests.support.components import build_composite_component, component_info
from tests.support.deps import (
    AForm,
    DeferringProvider,
    OtherForm,
    PlanEntry,
    plan_by_name,
    plan_entries,
)
from tests.support.forms import (
    GuardedTenantForm,
    build_post_request,
    isolated_form_registries,
)
from tests.support.helpers import (
    SignalSender,
    _ctx,
    _minimal_resolver,
    _resolver_with_form,
    build_mock_http_request,
    counting_provider,
    default_page_router_config,
    file_router_backend_from_params,
    file_router_config_entry,
    inspect_parameter,
    named_temp_py,
    next_framework_settings_component_backends_list,
    next_framework_settings_for_checks_backends_value,
    typing_optional,
)
from tests.support.pages import (
    build_nested_page,
    build_page_request,
    build_zone_request,
    path_under,
    record_path_calls,
    unified_view,
)
from tests.support.partial_requests import (
    action_uid,
    partial_meta,
    partial_request,
    plain_get,
    plain_request,
)
from tests.support.patches import (
    bound_dependency,
    importable_dir,
    patch_checks_components_manager,
    patch_checks_router_manager,
    patch_checks_router_manager_with_routers,
    patched_watch_sources,
    restored_provider_registry,
    restored_static_registries,
)
from tests.support.ports import IntentOnlyShaper
from tests.support.routers import (
    MalformedRootsRouter,
    OddComponentsNameRouter,
    OddSkipNamesRouter,
    RaisingComponentsRouter,
    RaisingRootsRouter,
    RaisingSkipNamesRouter,
    RootPagesRouter,
    SkippingRouter,
)
from tests.support.scenarios import tick_scenario
from tests.support.wizard import CountingWizardBackend


__all__ = [
    "BOOM_COMPONENTS_BACKEND",
    "COERCE_URL_VALUE_CASES",
    "DUMMY_COMPONENTS_BACKEND",
    "MALFORMED_WATCH_COMPONENTS_BACKEND",
    "RAISING_WATCH_COMPONENTS_BACKEND",
    "URL_BY_ANNOTATION_RESOLVE_CASES",
    "URL_KWARGS_RESOLVE_CASES",
    "AForm",
    "BoomComponentsBackend",
    "CoerceUrlValueCase",
    "ContextMarkerCase",
    "CountingWizardBackend",
    "DeferringProvider",
    "DummyComponentsBackend",
    "GuardedTenantForm",
    "IntentOnlyShaper",
    "MalformedRootsRouter",
    "MockAutoreloadSender",
    "OddComponentsNameRouter",
    "OddSkipNamesRouter",
    "OtherForm",
    "PlainStaticBackend",
    "PlanCase",
    "PlanEntry",
    "RaisingComponentsRouter",
    "RaisingRootsRouter",
    "RaisingSkipNamesRouter",
    "RecordingStaticBackend",
    "RootPagesRouter",
    "SignalSender",
    "SkippingRouter",
    "StaticAssetProvider",
    "UrlByAnnotationResolveCase",
    "UrlKwargsResolveCase",
    "WatchingComponentsBackend",
    "_ctx",
    "_minimal_resolver",
    "_resolver_with_form",
    "action_uid",
    "bound_dependency",
    "build_mock_http_request",
    "build_nested_page",
    "build_page_request",
    "build_post_request",
    "build_zone_request",
    "counting_provider",
    "default_page_router_config",
    "failing_watch_components_entry",
    "file_components_entry",
    "file_router_backend_from_params",
    "file_router_config_entry",
    "handler_declared_here",
    "importable_dir",
    "inspect_parameter",
    "isolated_form_registries",
    "named_temp_py",
    "next_framework_settings_component_backends_list",
    "next_framework_settings_for_checks_backends_value",
    "partial_meta",
    "partial_request",
    "patch_checks_components_manager",
    "patch_checks_router_manager",
    "patch_checks_router_manager_with_routers",
    "patched_watch_sources",
    "path_under",
    "plain_get",
    "plain_request",
    "plan_by_name",
    "plan_entries",
    "record_path_calls",
    "restored_provider_registry",
    "restored_static_registries",
    "tick_scenario",
    "typing_optional",
    "unified_view",
    "unwrapped_decorator",
    "watching_components_entry",
    "wraps_decorator",
]
