"""Page metadata folded from settings defaults and `page.py` segments, then resolved.

Only the value objects, the input dicts and the resolve and render seams are public.
"""

from . import ld
from .backends import HtmlMetadataRenderer, MetadataRenderer
from .dicts import (
    AlternatesDict,
    ArticleDict,
    BookDict,
    FeedDict,
    GooglebotDict,
    IconDict,
    IconsDict,
    LinkDict,
    MetadataDict,
    OpenGraphAudioDict,
    OpenGraphDict,
    OpenGraphImageDict,
    OpenGraphVideoDict,
    OtherIconDict,
    ProfileDict,
    RobotsDict,
    SiteMetadataDict,
    SiteTitleDict,
    Text,
    ThemeColorDict,
    TitleDict,
    TwitterDict,
    TwitterImageDict,
    TwitterPlayerDict,
    VerificationDict,
    ViewportDict,
)
from .markers import (
    RESET,
    Alternates,
    Article,
    Book,
    Breadcrumb,
    Crumb,
    Feed,
    Icon,
    Link,
    Metadata,
    OpenGraph,
    OpenGraphAudio,
    OpenGraphImage,
    OpenGraphVideo,
    Profile,
    Replace,
    ResolvedMetadata,
    Robots,
    ThemeColor,
    Twitter,
    TwitterImage,
    TwitterPlayer,
    Verification,
    Viewport,
)
from .resolve import absolute_url, resolve_metadata
from .scope import noindexed


__all__ = [
    "RESET",
    "Alternates",
    "AlternatesDict",
    "Article",
    "ArticleDict",
    "Book",
    "BookDict",
    "Breadcrumb",
    "Crumb",
    "Feed",
    "FeedDict",
    "GooglebotDict",
    "HtmlMetadataRenderer",
    "Icon",
    "IconDict",
    "IconsDict",
    "Link",
    "LinkDict",
    "Metadata",
    "MetadataDict",
    "MetadataRenderer",
    "OpenGraph",
    "OpenGraphAudio",
    "OpenGraphAudioDict",
    "OpenGraphDict",
    "OpenGraphImage",
    "OpenGraphImageDict",
    "OpenGraphVideo",
    "OpenGraphVideoDict",
    "OtherIconDict",
    "Profile",
    "ProfileDict",
    "Replace",
    "ResolvedMetadata",
    "Robots",
    "RobotsDict",
    "SiteMetadataDict",
    "SiteTitleDict",
    "Text",
    "ThemeColor",
    "ThemeColorDict",
    "TitleDict",
    "Twitter",
    "TwitterDict",
    "TwitterImage",
    "TwitterImageDict",
    "TwitterPlayer",
    "TwitterPlayerDict",
    "Verification",
    "VerificationDict",
    "Viewport",
    "ViewportDict",
    "absolute_url",
    "ld",
    "noindexed",
    "resolve_metadata",
]
